### ISSUE TITLE
Setup lua linter and formatter

### ISSUE THREAD

**Issue by bytemain** [version-fox/version-fox-plugins#24]
unified code style can reduce the cost of maintaining and reviewing code, and can find potential risks

**Comment by aooohan** [comment]
> unified code style can reduce the cost of maintaining and reviewing code, and can find potential risks

Agree! But how do we do that?

**Comment by bytemain** [comment]
just a idea, we ship a new binary called `vfox-dev`(or what ever).

```sh
vfox-dev lint
vfox-dev build
```

https://github.com/CppCXY/EmmyLuaCodeStyle

there are some code styles linters, but most of them need user clone them and build them on machine.

**Comment by bytemain** [comment]
or we can use dprint, it is a pluggable and configurable code formatting platform written in rust.

https://dprint.dev/

it has a lua plugin: https://github.com/RubixDev/dprint-plugin-stylua

**Comment by aooohan** [comment]
> I found that it support install by asdf, ahahahah

If we decide to use this, we can also implement a plug-in of our own. After taking a look, it is very easy. 😄

**Comment by aooohan** [comment]
> just a idea, we ship a new binary called `vfox-dev`(or what ever).
> 

I don't think we need to spend too much time on this, `dprint` is a good choice.

**Comment by bytemain** [comment]
ok, I will take a look on install dprint by vfox

**Comment by axdank** [comment]
we can also use [stylua](https://github.com/JohnnyMorganz/StyLua)

and add its configuration to the root of the project:
`stylua.toml`
```toml
column_width = 120
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"

[sort_requires]
enabled = false
```
